name: 'Tests'

on:
  push:

jobs:
  terraform-lint:
    runs-on: 'ubuntu-latest'
    env:
      TF_PATH: './terraform'
    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v3'
    - name: 'Run terraform fmt'
      uses: 'dflook/terraform-fmt-check@v1'
      with:
        path: '${{env.TF_PATH}}'
  python-lint:
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v3'
    - name: 'Setup python'
      uses: 'actions/setup-python@v4'
      with:
        python-version: '3.10'
    - name: 'Run flake8'
      uses: 'py-actions/flake8@v2'
      with:
        ignore: 'E501'
    - name: 'Run black'
      uses: 'psf/black@stable'
    - name: 'Run isort'
      uses: 'isort/isort-action@v1.1.0'
  pytest:
    runs-on: 'ubuntu-latest'
    env:
      APP_PATH: './app'
      SOURCE_PLAYLIST_ID: 'test'
      DESTINATION_PLAYLIST_ID': 'test'
      SPOTIFY_CLIENT_ID: 'test'
      SPOTIFY_CLIENT_SECRET: 'test'
      SPOTIFY_REDIRECT_URI: 'test'
      GCP_PROJECT: 'test'
      GCP_SECRET_ID: 'test'
    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v3'
    - name: 'Setup python'
      uses: 'actions/setup-python@v4'
      with:
        python-version: '3.10'
    - name: 'Install dependencies'
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r $APP_PATH/requirements.txt
    - name: 'Run pytest'
      run: 'PYTHONPATH=$APP_PATH pytest tests'
